### ISSUE TITLE
Error Installing environment

### ISSUE THREAD

**Issue by hamza-712** [xarakas/ETSC#4]
I built my conda env using instructions. for python 3.7. 
I can't install tensorflow==1.14.0 cuz tensorflow==2.x onwards is compatible.

**Comment by xarakas** [comment]
Hi, can you please try with python 3.6 conda env?

**Comment by hamza-712** [comment]
Worked well. I created modified code for other algorithms too. Should I make a PR?

**Comment by xarakas** [comment]
Sure, feel free. Thank you!
